/**
 * TierScope model registry  -  the single update point for the tracked model
 * catalog. The backend sync pipeline upserts every entry here into the
 * database (see api/sync.ts). To add or refresh models, edit this file (or
 * let the automated upstream refresh rewrite it  -  see docs/DATA-PIPELINE.md).
 *
 * Metrics are point-in-time snapshots from public leaderboards
 * (LMArena, Artificial Analysis, ARC Prize, official model cards),
 * captured 2026-08-21. `null` = not publicly available.
 */

import type { ModelKind } from "./tiers";

export interface RegistryEntry {
  slug: string;
  name: string;
  lab: string;
  kind: ModelKind;
  license: string | null;
  /** total parameters, billions */
  paramsB: number | null;
  /** active parameters per token (MoE), billions */
  activeB: number | null;
  /** context window, thousands of tokens */
  ctxK: number | null;
  /** USD per 1M input tokens */
  inPrice: number | null;
  /** USD per 1M output tokens */
  outPrice: number | null;
  /** ISO release date */
  released: string;
  summary: string;
  tags: string[];
  metrics: {
    arena: number | null;
    aa: number | null;
    arc2: number | null;
    swe: number | null;
    gpqa: number | null;
  };
}

export const REGISTRY_AS_OF = "2026-08-21";

export const MODEL_REGISTRY: RegistryEntry[] = [
  // ─────────────────────────── Frontier (proprietary) ───────────────────────────
  {
    slug: "claude-opus-5",
    name: "Claude Opus 5",
    lab: "Anthropic",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 5,
    outPrice: 25,
    released: "2026-07-24",
    summary:
      "Anthropic's flagship. Leads the Artificial Analysis index and dominates ARC-AGI-3 interactive reasoning; thinking on by default.",
    tags: ["reasoning", "agents", "coding", "long-context"],
    metrics: { arena: 1522, aa: 63, arc2: 90.4, swe: null, gpqa: null },
  },
  {
    slug: "claude-fable-5",
    name: "Claude Fable 5",
    lab: "Anthropic",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 10,
    outPrice: 50,
    released: "2026-06-10",
    summary:
      "Anthropic's ceiling model for the hardest reasoning tasks; best verified ARC-AGI-1 score to date.",
    tags: ["reasoning", "research", "math"],
    metrics: { arena: 1525, aa: 62, arc2: 89.2, swe: null, gpqa: null },
  },
  {
    slug: "claude-mythos-5",
    name: "Claude Mythos 5",
    lab: "Anthropic",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 10,
    outPrice: 50,
    released: "2026-06-02",
    summary:
      "Limited-access capability ceiling from Anthropic; highest Arena rating on record.",
    tags: ["reasoning", "limited-access"],
    metrics: { arena: 1531, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "sonnet-5",
    name: "Claude Sonnet 5",
    lab: "Anthropic",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 3,
    outPrice: 15,
    released: "2026-06-18",
    summary:
      "Balanced agents-and-coding workhorse in the Claude 5 family at mid-tier pricing.",
    tags: ["coding", "agents", "value"],
    metrics: { arena: 1479, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    lab: "OpenAI",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 5,
    outPrice: 30,
    released: "2026-07-09",
    summary:
      "OpenAI's top reasoning tier of the GPT-5.6 family; highest verified ARC-AGI-2 score and a coding favorite.",
    tags: ["reasoning", "coding", "agents"],
    metrics: { arena: 1514, aa: 61, arc2: 92.5, swe: null, gpqa: null },
  },
  {
    slug: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    lab: "OpenAI",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 2,
    outPrice: 12,
    released: "2026-07-09",
    summary:
      "Default production tier of GPT-5.6  -  fast, high-volume general reasoning after an 80% price cut.",
    tags: ["general", "production", "value"],
    metrics: { arena: 1489, aa: null, arc2: 83.9, swe: null, gpqa: null },
  },
  {
    slug: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    lab: "OpenAI",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 400,
    inPrice: 0.2,
    outPrice: 1.2,
    released: "2026-08-06",
    summary:
      "Lightweight GPT-5.6 variant; default for ChatGPT Free/Go tiers with a Think mode.",
    tags: ["budget", "consumer", "fast"],
    metrics: { arena: null, aa: null, arc2: 59.6, swe: null, gpqa: null },
  },
  {
    slug: "gpt-5.5-pro",
    name: "GPT-5.5 Pro",
    lab: "OpenAI",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 30,
    outPrice: 180,
    released: "2026-04-23",
    summary:
      "OpenAI's max-compute reasoning offering  -  strong on agentic tool use and research workflows.",
    tags: ["reasoning", "research", "agents"],
    metrics: { arena: 1510, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    lab: "Google",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 2,
    outPrice: 12,
    released: "2026-04-14",
    summary:
      "Google's science and long-context flagship; leads GPQA Diamond among proprietary models.",
    tags: ["science", "long-context", "multimodal"],
    metrics: { arena: 1505, aa: null, arc2: null, swe: 80.6, gpqa: 94.3 },
  },
  {
    slug: "gemini-3.7-flash",
    name: "Gemini 3.7 Flash",
    lab: "Google",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1048,
    inPrice: null,
    outPrice: null,
    released: "2026-08-13",
    summary:
      "The price-performance shocker of August 2026  -  84.6% on ARC-AGI-2 at $0.25 per task, 1M-token input.",
    tags: ["fast", "value", "production"],
    metrics: { arena: null, aa: null, arc2: 84.6, swe: null, gpqa: null },
  },
  {
    slug: "gemini-3-flash",
    name: "Gemini 3 Flash",
    lab: "Google",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 2,
    outPrice: 12,
    released: "2026-02-10",
    summary:
      "Speed-and-cost optimized Gemini 3 tier with strong agentic benchmark results.",
    tags: ["fast", "value"],
    metrics: { arena: 1505, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "grok-4.6",
    name: "Grok 4.6",
    lab: "xAI",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: 500,
    inPrice: 2,
    outPrice: 6,
    released: "2026-08-12",
    summary:
      "xAI's return to the frontier  -  tuned for coding, agentic work and long-running tasks, tied at 61 on the AA index.",
    tags: ["coding", "agents", "real-time"],
    metrics: { arena: 1499, aa: 61, arc2: 67.1, swe: null, gpqa: null },
  },
  {
    slug: "muse-spark-1.2",
    name: "Muse Spark 1.2",
    lab: "Meta",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: null,
    inPrice: null,
    outPrice: null,
    released: "2026-04-30",
    summary:
      "Meta's first closed frontier model  -  no weights, no architecture paper  -  as Meta stepped back from the open frontier.",
    tags: ["general", "closed"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "composer-2.5",
    name: "Composer 2.5",
    lab: "Cursor",
    kind: "frontier",
    license: null,
    paramsB: null,
    activeB: null,
    ctxK: null,
    inPrice: null,
    outPrice: null,
    released: "2026-06-25",
    summary:
      "Cursor's in-house coding model, optimized for multi-file edits and agentic IDE loops.",
    tags: ["coding", "ide", "agents"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: null },
  },

  // ─────────────────────────────── Open-weight ───────────────────────────────
  {
    slug: "kimi-k3",
    name: "Kimi K3",
    lab: "Moonshot AI",
    kind: "open",
    license: "Modified MIT",
    paramsB: 2800,
    activeB: 50,
    ctxK: 1000,
    inPrice: 3,
    outPrice: 15,
    released: "2026-07-15",
    summary:
      "Trillion-scale open MoE that ranks #3 overall on the Artificial Analysis index  -  the open-weight frontier, and #1 on the Frontend Code Arena.",
    tags: ["open-weight", "coding", "agents", "moe"],
    metrics: { arena: 1500, aa: 61, arc2: 60.4, swe: 76.8, gpqa: 93.5 },
  },
  {
    slug: "kimi-k2.5",
    name: "Kimi K2.5",
    lab: "Moonshot AI",
    kind: "open",
    license: "Modified MIT",
    paramsB: 1000,
    activeB: 32,
    ctxK: 256,
    inPrice: 0.73,
    outPrice: 3.49,
    released: "2026-04-08",
    summary:
      "Frontier-quality open model at aggressive pricing; strong agentic and tool-use performance.",
    tags: ["open-weight", "value", "agents"],
    metrics: { arena: 1466, aa: null, arc2: null, swe: 76.8, gpqa: 87.6 },
  },
  {
    slug: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    lab: "DeepSeek",
    kind: "open",
    license: "MIT",
    paramsB: 1600,
    activeB: 49,
    ctxK: 1000,
    inPrice: null,
    outPrice: null,
    released: "2026-08-13",
    summary:
      "DeepSeek's open flagship  -  matches Gemini 3.1 Pro on SWE-bench Verified and improves agentic production behavior.",
    tags: ["open-weight", "coding", "reasoning"],
    metrics: { arena: 1467, aa: null, arc2: 61.3, swe: 80.6, gpqa: 90.1 },
  },
  {
    slug: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    lab: "DeepSeek",
    kind: "open",
    license: "MIT",
    paramsB: 284,
    activeB: 13,
    ctxK: 1000,
    inPrice: 0.66,
    outPrice: 1.98,
    released: "2026-07-31",
    summary:
      "The low-cost open-weight benchmark story: 61.4% on ARC-AGI-2 at $0.04 per task.",
    tags: ["open-weight", "budget", "fast"],
    metrics: { arena: 1461, aa: null, arc2: 61.4, swe: 79.0, gpqa: 88.1 },
  },
  {
    slug: "glm-5.3",
    name: "GLM-5.3",
    lab: "Z.ai",
    kind: "open",
    license: "MIT",
    paramsB: 744,
    activeB: 40,
    ctxK: 1000,
    inPrice: 1.4,
    outPrice: 4.4,
    released: "2026-06-20",
    summary:
      "Fastest self-hostable frontier-class model; MIT-licensed and outscoring US flagships on agentic coding.",
    tags: ["open-weight", "self-host", "coding"],
    metrics: { arena: 1483, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "qwen-3.8-max",
    name: "Qwen 3.8 Max",
    lab: "Alibaba",
    kind: "open",
    license: "Apache 2.0 (text)",
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 2,
    outPrice: 6,
    released: "2026-08-05",
    summary:
      "Alibaba's multimodal APAC frontier with text-only open weights; long autonomous agentic runs.",
    tags: ["open-weight", "multimodal", "agents"],
    metrics: { arena: 1491, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "qwen-3.6-27b",
    name: "Qwen 3.6 27B",
    lab: "Alibaba",
    kind: "open",
    license: "Apache 2.0",
    paramsB: 27,
    activeB: 27,
    ctxK: 256,
    inPrice: null,
    outPrice: null,
    released: "2026-05-28",
    summary:
      "Genuinely small open model that runs on a single GPU  -  the other pole of the bifurcated open ecosystem.",
    tags: ["open-weight", "small", "edge"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "minimax-m3",
    name: "MiniMax M3",
    lab: "MiniMax",
    kind: "open",
    license: "Custom (open weights)",
    paramsB: null,
    activeB: null,
    ctxK: 1000,
    inPrice: 0.6,
    outPrice: 2.4,
    released: "2026-06-12",
    summary:
      "Open-weight agentic coding contender at 80.5% SWE-bench Verified and budget pricing.",
    tags: ["open-weight", "coding", "value"],
    metrics: { arena: 1455, aa: null, arc2: null, swe: 80.5, gpqa: null },
  },
  {
    slug: "llama-4-maverick",
    name: "Llama 4 Maverick",
    lab: "Meta",
    kind: "open",
    license: "Llama Community",
    paramsB: 400,
    activeB: 17,
    ctxK: 1000,
    inPrice: null,
    outPrice: null,
    released: "2025-04-05",
    summary:
      "Meta's last open frontier release before the pivot to closed models; still widely self-hosted.",
    tags: ["open-weight", "moe", "self-host"],
    metrics: { arena: null, aa: null, arc2: null, swe: 65.0, gpqa: 69.8 },
  },
  {
    slug: "llama-4-scout",
    name: "Llama 4 Scout",
    lab: "Meta",
    kind: "open",
    license: "Llama Community",
    paramsB: 109,
    activeB: 17,
    ctxK: 1000,
    inPrice: null,
    outPrice: null,
    released: "2025-04-05",
    summary: "Smaller Llama 4 MoE  -  long context, easy fine-tuning target.",
    tags: ["open-weight", "fine-tune"],
    metrics: { arena: null, aa: null, arc2: null, swe: 68.0, gpqa: 73.7 },
  },
  {
    slug: "mistral-large-3",
    name: "Mistral Large 3",
    lab: "Mistral AI",
    kind: "open",
    license: "Apache 2.0",
    paramsB: 675,
    activeB: 41,
    ctxK: 256,
    inPrice: null,
    outPrice: null,
    released: "2025-12-02",
    summary: "Mistral's open flagship MoE, a European favorite for sovereign deployments.",
    tags: ["open-weight", "sovereign", "moe"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "mistral-small-4",
    name: "Mistral Small 4",
    lab: "Mistral AI",
    kind: "open",
    license: "Apache 2.0",
    paramsB: 119,
    activeB: 6.5,
    ctxK: 256,
    inPrice: null,
    outPrice: null,
    released: "2026-03-18",
    summary: "Efficient small MoE for on-prem and edge deployments.",
    tags: ["open-weight", "small", "edge"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: null },
  },
  {
    slug: "nemotron-ultra-253b",
    name: "Nemotron Ultra 253B",
    lab: "NVIDIA",
    kind: "open",
    license: "NVIDIA Open",
    paramsB: 253,
    activeB: 253,
    ctxK: 128,
    inPrice: null,
    outPrice: null,
    released: "2025-04-08",
    summary: "Dense open reasoning model from NVIDIA, tuned for math and science.",
    tags: ["open-weight", "reasoning", "dense"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: 76.0 },
  },
  {
    slug: "deepseek-r1",
    name: "DeepSeek R1",
    lab: "DeepSeek",
    kind: "open",
    license: "MIT",
    paramsB: 671,
    activeB: 37,
    ctxK: 164,
    inPrice: 0.55,
    outPrice: 2.19,
    released: "2025-01-20",
    summary: "The open reasoning model that reset the cost curve in early 2025; a living classic.",
    tags: ["open-weight", "reasoning", "classic"],
    metrics: { arena: 1350, aa: null, arc2: null, swe: 49.2, gpqa: 71.5 },
  },
  {
    slug: "gemma-4-27b",
    name: "Gemma 4 27B",
    lab: "Google",
    kind: "open",
    license: "Gemma Terms",
    paramsB: 27,
    activeB: 27,
    ctxK: 128,
    inPrice: null,
    outPrice: null,
    released: "2026-05-20",
    summary: "Google's small open line  -  phone-and-laptop class, popular for on-device apps.",
    tags: ["open-weight", "small", "on-device"],
    metrics: { arena: null, aa: null, arc2: null, swe: null, gpqa: null },
  },
];
